### ISSUE TITLE
NOTESTOCKでの検索結果に「見つかりませんでした」表示が残る

### ISSUE THREAD

**Issue by ghost** [accelforce/Tusky#1]
検索→NOTESTOCKタブにおいて、結果が出た場合でも「見つかりませんでした」という表示が重なる。

* * * *
- Tusky Version: Yuito 2.0.0
- Android Version: Android 10
- Android Device: OnePlus 5T
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyori19** [comment]
報告ありがとうございます。

現象は再現できているのですが、一通り調査してみて今のところ原因がわからない状態です。
今後も引き続き調査はさせていただきます。
しばらくお待ちください。

**Comment by kyori19** [comment]
Fixed in 9899b99e1eccc1efa9bade5e788d84b83bca95d0
