### ISSUE TITLE
Support of Animated PNG emoji

### ISSUE THREAD

**Issue by inkybr** [accelforce/Tusky#11]
Tusky doesn't support APNG([apng emoji example](https://s3.ap-northeast-1.amazonaws.com/g0v-social/custom_emojis/images/000/044/746/original/17d89332ba939012.png)), and [it seems it doesn't plan to](https://github.com/tuskyapp/Tusky/issues/472).
Yuito doesn't supports APNG either.

Other Android client like Fedilab already supports it, and I purchased it just to see animated emoji.

I find some useful libraries upon a quick search.
Line has [a library that supports APNG on Android](https://github.com/line/apng-drawable). 
There are also
https://github.com/penfeizhou/APNG4Android and https://github.com/oupson/Kapng-Android

Hopefully these are helpful information and help Yuito support animated PNG too. Thanks.

* * * *
- [O] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyori19** [comment]
Resolved in tuskyapp#2064. Closing
