### ISSUE TITLE
フォローやリモートフォロー

### ISSUE THREAD

**Issue by kuloma** [accelforce/Tusky#13]
< フォローやリモートフォローをしようとするとブラウザーからしか出来ない >

* * * *
- Yuito Version:3:7:2
- Android Version:10
- Android Device:GALAXY
- Mastodon instance (fedibird.com):

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] フォローやリモートフォローをしようとしたり、フォローリクエストを許可しようとするとエラーが置きブラウザからでないとできません。

**Comment by kyori19** [comment]
発生するエラーは共有できますか？

**Comment by kyori19** [comment]
fedibird.comとの互換性問題

**Comment by noellabo** [comment]
Pleromaの同名機能のプロパティ（subscripting）との競合ということで、Fedibird系サーバに修正を入れて対応します。

**Comment by kuloma** [comment]
共有できるかは試してないので分かりません

2021年1月23日(土) 午前0:29 kyori19 <notifications@github.com>:

**Comment by noellabo** [comment]
fedibird.com nightly.fedibird.com では解消しました。
https://github.com/fedibird/mastodon/commit/c6c5294f128f47e872bb3edb954feb3455717b58

**Comment by kyori19** [comment]
@noellabo ありがとうございますぅぅうううう
