### ISSUE TITLE
Quick Toot Area を非表示にする機能

### ISSUE THREAD

**Issue by yukiyalien** [accelforce/Tusky#14]
Quick Toot Areaを非表示にできるオプションがあると大変ありがたいです。
* * * *
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyori19** [comment]
対応版を用意しましたが動作検証が不十分なのでpre-releaseです
Store版は出ませんがapkはダウンロードできます

https://github.com/accelforce/Yuito/releases/tag/v4.0.0-beta.0
