### ISSUE TITLE
Support for pleroma specific features? 

### ISSUE THREAD

**Issue by ghost** [accelforce/Tusky#15]
So, I am a pleroma user myself, and I would love pleroma specific features to be added to the client like, support for pleroma stickers, text formatting, direct messages, Pleroma chat and custom client name or something... 

There are multiple different client that already has those features like husky but husky hasn't gotten an update in over 10 months, and it's getting slow and old, and honestly i love your client and the sheer amount of features it has :)

**Comment by kyori19** [comment]
I don't have any Pleroma accounts and I still have no intention to implement Pleroma features.
As you pointed out, I can extract codes from Husky, but maintaining it is really hard.
Husky has latest commit which is pushed at three months ago, so I think its development still continues.
