### ISSUE TITLE
Support for pleroma "Chat" and DMs ? 

### ISSUE THREAD

**Issue by ghost** [accelforce/Tusky#16]
So, for pleroma Instances there is a feature called "Chat" or "Chatting" which acts like a public messaging channel for everyone who is signed up for the instance, some Frontends have this like SoapboxFE, BloatFE, Husky and Fedilab.
Having a tab on Yuito for it would be great for pleroma users...

Also, having the ability to change how the name of our client appear to other users with a custom redirect would be a nice feature, but you don't have to add it since it's not necessary, it's just fun doing some creative things with it... But chatting is quiet necessary for me as a pleroma user.

Thank you :)

**Comment by kyori19** [comment]
I don't have a plan to support Pleroma for now, because I have no accounts on Pleroma instance.

FYI, open "About" in the application drawer and tap space under Yuito logo ("AccelF" logo in dark theme) six times. You will find a hidden feature.
