### ISSUE TITLE
keyboard opens after backing out of a fullscreen image

### ISSUE THREAD

**Issue by ryanayoung** [accelforce/Tusky#17]
After opening any image/gif from any timeline, backing out of it opens the onscreen keyboard. This is not expected action and interrupts getting back to the timeline. This happens with either the android back button, the yuito back arrow on gifs, and swiping away still images. 

* * * *
- Yuito Version: 4.1.4
- Android Version: 12
- Android Device: Samsung Galaxy note20 5G
- Mastodon instance (if applicable):

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyori19** [comment]
I could not reproduce the problem. Can you provide more informations?

**Comment by kyori19** [comment]
I will close this issue due to inactivity. Please reopen if the problem continues.

**Comment by ryanayoung** [comment]
Sorry, I just got back to this. I'm still having this problem. I've Uninstalled and reinstalled. I tried with both the built in Samsung keyboard and the google gboard and it still happens. I installed Tusky and it does not happen in that app.

I recorded my screen to show an example of what's happening in yuito and opened tusky to compare.
https://www.dropbox.com/s/2k9r8rkbbtvtoo9/2022-05-04%2009.59.28.mp4?dl=0

**Comment by kyori19** [comment]
I think that should be the problem of your Samsung device because I have 2 devices without this issue.
For a workaround, disabling `Use quick compose field' setting in the application setting might help you avoiding the problem.
Please try it and tell me whether the problem is fixed or not.

**Comment by ryanayoung** [comment]
Thank you for the response. Disabling the quick compose field does in fact remove the problem, which is actually great as I prefer not to use the quick compose field anyway, and hadn't realized it could be disabled.  Thank you.
