### ISSUE TITLE
Show seconds absolute time

### ISSUE THREAD

**Issue by Hikali-47041** [accelforce/Tusky#18]
## 概要
[v4.1.5](https://github.com/accelforce/Yuito/releases/tag/v4.1.5) から絶対時刻において秒の表示がなくなりました。
(これはTusky 17.0では絶対時刻において秒が表示されています。もしかしたらTusky側での変更があった可能性もあり得ます)

## 要望
以前のように絶対時刻に秒を表示するようなオプションを設定でつけていただくとありがたいです。  
さらに、設定でカスタムの時刻フォーマットが使えるようになるとさらに便利になると思います。

* * * *
- Yuito Version: 4.1.5
- Android Version:  11 RQ3A.211001.001
- Android Device: Pixel 4a (sunfish)
- Mastodon instance (if applicable): mental.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyori19** [comment]
次リリースにて修正します。
