### ISSUE TITLE
書き込み画面でのハッシュタグの文字色

### ISSUE THREAD

**Issue by ghost** [accelforce/Tusky#2]
書き込み画面で、文章に続けて(スペースを挿入せずに)ハッシュを打ち込んだ場合でも、ハッシュタグの文字色を青色にして欲しい。

* * * *
- Tusky Version: Yuito 2.0.0
- Android Version: Android 10
- Android Device: OnePlus 5T
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyori19** [comment]
@spokekit accelforce@8be0989a7330fc0b500335df9fcbf467171a590a にて修正しました
次回リリース(近日予定)にて反映されます
