### ISSUE TITLE
Feature Request: Add Edit Toot Functionality

### ISSUE THREAD

**Issue by lehitoskin** [accelforce/Tusky#23]
Since Mastodon v4.X supports editing toots, it would be nice to have this functionality added to the app. I checked Tusky and there doesn't seem to be any sort of mention about it.
![edit](https://user-images.githubusercontent.com/2506703/211218794-191e17cf-d0c7-41dd-a370-eaa9c68cc021.jpg)

* * * *
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyori19** [comment]
I'm sure that Tusky contributors will implement it, so I will wait for it.
