### ISSUE TITLE
Calckey/Misskey support 

### ISSUE THREAD

**Issue by ThatOneCalculator** [accelforce/Tusky#24]
Because Tusky doesn't want to implement it, would you consider implementing Calckey/Misskey API support so that users of those platforms can also use Yuito? https://calckey.social/api-doc

* * * *
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyori19** [comment]
Yuito only supports Mastodon officially.
Other platforms won't be supported because I cannot maintain them.
