### ISSUE TITLE
タイムラインの一番上の投稿がミュートされない

### ISSUE THREAD

**Issue by ghost** [accelforce/Tusky#3]
タイムラインの一番上に表示されている投稿はミュート設定していても非表示にならない
ホームタイムラインにて確認。

* * * *
- Yuito Version: 2.0.0
- Android Version: Android 10
- Android Device: Oneplus 5T
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ghost** [comment]
言葉足らずだったので補足
正確には、「ミュート設定していてもアプリ起動後、タイムラインの読み込み時に非表示にされることがない」。
その場でミュートした場合や、タブをリセットした場合には非表示になります。

**Comment by kyori19** [comment]
問題が解消する可能性があるコミットがマージされました
次回リリース後にも現象が発生するかどうか確認をお願いします

accelforce@e72bdcaf422fdbb0200133f817c6cb9d5debb986

**Comment by kyori19** [comment]
https://github.com/accelforce/Yuito/blob/0e8aa1f48b3275e54540fb267fe767a47f3b4f39/app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java#L395

id < max_id の投稿しか帰ってこないので、先頭の投稿が除去されることはありえない実装になっている(先頭はレスポンスに含まれない => フィルターで除外された, あるいは削除されたことを検出しようがない)
DBから何故消えていないのかについては別途要調査

どちらにせよ本家Issueっぽいので不明ならそちらも検討

**Comment by kyori19** [comment]
ミュートの挙動が変わったのでおそらく解消
