### ISSUE TITLE
Warning if user forgets alt text

### ISSUE THREAD

**Issue by ghost** [accelforce/Tusky#31]
Yuito already displays a yellow warning icon if the user forgets to caption images, but I miss it too often and then I suddenly realise I screwed up and dive in to edit my post.

In those cases, it would be great if there was an option to show a dialog when you press 'toot!' saying something along the lines of 'looks like you have not added alt text! are you sure you want to publish?'

* * * *
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyori19** [comment]
I don't like such warning so I won't implement this actively. There's same issue in Tusky repo, so please track that.
https://github.com/tuskyapp/Tusky/issues/1049
