### ISSUE TITLE
通知タブに内容が表示されないことがある

### ISSUE THREAD

**Issue by ghost** [accelforce/Tusky#4]
アプリ起動後、ローカルタイムラインタブ(か連合タイムラインタブ)へ→投稿が読み込まれるのを待つ→投稿が読み込まれたら、1.5秒以上(連合タイムラインの場合は0.5秒以上くらい)そのまま待つ→通知タブへ→読み込み中を示す青いグルグル含め、何も表示されない。

* * * *
- Yuito Version: 2.0.0
- Android Version: Android 10
- Android Device: OnePlus 5T
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyori19** [comment]
@spokekit 設定に存在する「ViewPagerのoffpageScreenLimitを増やす」を有効にしたうえで問題が解消するか確認していただけますでしょうか？

**Comment by kyori19** [comment]
Fixed by tuskyapp#1905
