### ISSUE TITLE
設定画面の一部項目が改行されず見切れる

### ISSUE THREAD

**Issue by ghost** [accelforce/Tusky#5]
フォントサイズ、表示サイズ、画面サイズにより設定画面の一部項目が改行されず右端で見切れる。

* * * *
- Yuito Version: 2.1.0
- Android Version: Android 10
- Android Device: OnePlus 5T
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyori19** [comment]
改行されない設定というのは具体的にどの設定でしょうか？
スクリーンショットなど見せていただけると助かります

**Comment by ghost** [comment]
自分の環境で確認できた限りでは、「モバイルネットワーク..」「トゥートのテキストサイズ...」「ViewPager...」「HTLのストリーミング...」の4つが改行されないようです。

![Screenshot_20200504-162203](https://user-images.githubusercontent.com/62984449/80944278-1d507380-8e24-11ea-9ab5-87203854c71e.png)
![Screenshot_20200504-162221](https://user-images.githubusercontent.com/62984449/80944281-1f1a3700-8e24-11ea-9ea9-cdcfacadb88b.png)
![Screenshot_20200504-162524](https://user-images.githubusercontent.com/62984449/80944286-22152780-8e24-11ea-8cff-3009262536de.png)

**Comment by kyori19** [comment]
accelforce@1f05df670b93f5312e1cac1a0b4a3ef30f732d24 で修正されたと思います
一度closeしますので次回更新後に改善しなければ再度openしてください
