### ISSUE TITLE
タブタップ時の「Jump to top」と「Reset tab」が重なる

### ISSUE THREAD

**Issue by ghost** [accelforce/Tusky#6]
フォントサイズ、表示サイズ、画面サイズによりタブタップ時に表示される「Jump to top」と「Reset tab」の文言の端が重なる。

* * * *
- Yuito Version: 2.1.0
- Android Version: Android 10
- Android Device: OnePlus 5T
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyori19** [comment]
accelforce@c028c0f1f66dbf713875e85a2229d9c849ee7ccb にてデザインを変更し修正
