### ISSUE TITLE
【要望】 アカウントの設定>フィルター 項に「プロフィール」が欲しい

### ISSUE THREAD

**Issue by ghost** [accelforce/Tusky#7]
アカウントの設定>フィルター 項に「プロフィール」が欲しい。

* * * *
- Yuito Version: 2.1.0
- Android Version: Android 10
- Android Device: OnePlus 5T
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ghost** [comment]
Mastodon Webに準拠して除外対象として「プロフィール」の項目をサポートしてほしいです。

**Comment by kyori19** [comment]
accelforce@e6089ebb8429ee90fe9d93197c7bb31eb766d729 で実装しました
次回リリースまでお待ち下さい
