### ISSUE TITLE
【要望】 新規投稿画面での投稿プライバシーがQuick Toot Areaでの設定と同じにならないようにして欲しい

### ISSUE THREAD

**Issue by ghost** [accelforce/Tusky#8]
新規投稿画面での投稿プライバシーの設定がQuick Toot Areaでの投稿プライバシーの設定に引きずられるのはアカウントの設定>デフォルトの投稿プライバシーの設定があることを考えても分かりづらいと思うのですが、どうでしょうか。

* * * *
- Yuito Version: 2.1.0
- Android Version: Android 10
- Android Device: OnePlus 5T
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kyori19** [comment]
動作を切り替える設定を追加しようと思うのですが、どこまで引きずらないようにした方がいいでしょうか？

1.  簡易投稿欄が空欄のときデフォルトを使用し、簡易投稿欄に文字列があるとき簡易投稿欄の設定を適用
1. 常にデフォルトを使用

**Comment by ghost** [comment]
自分はQuick Toot Areaを全く使わないのでコメントし難いですが、前者の方がQuick Toot Area利用者にとって利になるのなら、前者でいいのではないでしょうか。

**Comment by kyori19** [comment]
Related to #14
