### ISSUE TITLE
Signature

### ISSUE THREAD

**Issue by IzzySoft** [accelforce/Tusky#9]
[Issue text goes here].

* * * *
- Tusky Version: 3.6.3
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

Looks like the APK attached to the release is not properly signed:

```
$ apksigner verify --verbose Yuito-v3.6.3.apk 
DOES NOT VERIFY
ERROR: No JAR signatures
```

If your app is supposed to support Android versions 7 and below, it will need v1 signing as well (v2 was only introduced with Android 8 IIRC, but definitely not before 7 – Tusky says to support Android 5+). Could you please tick all those signing boxes (v1, v2, v3) when producint an APK – and replace the APK at releases with a fully-signed one? Thanks a lot!

PS: note that your issue template still asks for "Tusky Version", you might wish to update that as well :wink: I was referring to Yuito 3.6.3 here.

**Comment by kyori19** [comment]
Thanks for reporting the issue!
I didn't know what "signing versions" mean.
I uploaded the new apk of the latest release as Yuito-v3.6.3-re.apk.
Please check it and close this issue if there's no problems.

And I will also fix the issue template. Really thanks!

**Comment by IzzySoft** [comment]
Thanks for your fast response and the fix! Yeah, versions applies to signing here, not the other way around :wink: Basically, v1 was only JAR signing (protecting the components), while v2 introduced APK signing (protecting the entire package), and v3 improved on v2. There's of course some more to it – but that puts it in "very easy terms".

I just saw some other Tusky remains: your entire Fastlane structure still has the descriptions, screenshots etc. from Tusky. As it covers quite a few languages, you might wish to drop those you cannot cater currently (they can always be added back) and concentrate on those you can. `en-US` is often used as fallback, and thus should definitely remain. Japanese of course could be added :wink:

Just in case you're not familiar with Fastlane: it's full name is "Fastlane Supply", and it's used to deploy apps to e.g. Google Play. Other "stores" like [F-Droid](https://f-droid.org/) or [my repo](https://apt.izzysoft.de/fdroid) (where [your app will become available](https://apt.izzysoft.de/fdroid/index/apk/net.accelf.yuito) in less than 8 hours) also use it. For a quick reference of the structure (the official documentation is a bit difficult for that), you can use [my snippet here](https://gitlab.com/snippets/1895688).
